---
- name: Update apt
  ansible.builtin.apt:
    force_apt_get: yes
    update_cache: yes
    cache_valid_time: 0

- name: Restart Incus
  ansible.builtin.systemd_service:
    name: incus.service
    state: restarted
