---

# A list of all the hosts which should have host records added to the /etc/hosts file
hostsfile_hosts: "{{ groups['all'] }}"

additional_hostsfile_hosts: []
# additional_hostsfile_hosts:
#   - { ip: "127.0.0.1", hostname: "{{ xxxxx_variable_xxxxx }}" }
